replicaCount: 1

config:
  gpgsql:
    dnssec: true
    host: pgsql
    dbname: pdns
    user: pdns
    password: pdns
  inlineConfig: |
    master=yes
    slave=no
    default-soa-edit=INCEPTION-INCREMENT
    default-soa-edit-signed=INCEPTION-INCREMENT

image:
  repository: helios.a/powerdns
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 53
  loadBalancerIP: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
