apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "minecraft.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "minecraft.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: eula
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
          args:
            - -ec
            - echo eula=true >eula.txt
          volumeMounts:
            - mountPath: /var/lib/minecraft
              name: runtime
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/minecraft
              name: runtime
            - mountPath: /var/lib/minecraft/server.properties
              name: config
              subPath: server.properties
            - mountPath: /var/lib/minecraft/world
              name: world
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe: &probe
            tcpSocket:
              port: minecraft
          readinessProbe: *probe
          startupProbe:
            <<: *probe
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: runtime
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "minecraft.fullname" . }}
        - name: world
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "minecraft.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
