---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "overviewer.fullname" . }}-config
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
    app.kubernetes.io/component: render
data:
  config.py: |
    worlds[{{ .Values.config.worldName | quote }}] = "/var/lib/minecraft/world"
    outputdir = "/usr/share/nginx/html"
    texturepath = "/opt/textures"
    customwebassets = "/overviewer/webassets"
    defaultzoom = {{ .Values.config.defaultZoom }}
    processes = {{ .Values.config.processes }}

    from .observer import MultiplexingObserver, LoggingObserver, JSObserver
    loggingObserver = LoggingObserver()
    jsObserver = JSObserver(outputdir)
    observer = MultiplexingObserver(loggingObserver, jsObserver)
    {{- .Values.config.inlineConfig | nindent 4 }}

    end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)]
    {{- range .Values.config.renders }}
    renders[{{ .name | quote }}] = {
        "title": {{ .title | default (title .name) | quote }},
        "world": {{ $.Values.config.worldName | quote }},
        {{- if .dimension }}
        "dimension": {{ .dimension | quote }},
        {{- end }}
        "rendermode": {{ .renderMode }},
        "markers": [
            {{- range .markers }}
            {{ get $.Values.config.markers . }},
            {{- end }}
        ],
    }
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "overviewer.fullname" . }}-webassets
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
    app.kubernetes.io/component: render
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>{title}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="generator" content="Minecraft-Overviewer {version}" />
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <script type="text/javascript" src="overviewerConfig.js"></script>
        <script type="text/javascript" src="overviewer.js"></script>
        <script type="text/javascript" src="baseMarkers.js"></script>
        <link rel="stylesheet" href="leaflet.css" />
        <script src="leaflet.js"></script>
        <link rel="stylesheet" href="overviewer.css" type="text/css" />
      </head>
      <body onload="overviewer.util.initialize()">
        <div id="mcmap"></div>
        <script type="text/javascript">
            overviewer.util.ready(function() {
              overviewer.worldCtrl.remove();
              overviewer.compass.remove();
              overviewer.map.attributionControl.remove();
            });
        </script>
      </body>
    </html>
