{{- if .Values.persistence.enabled }}
{{- if .Values.schedule.render }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "overviewer.fullname" . }}-render
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
    app.kubernetes.io/component: render
spec:
  schedule: {{ .Values.schedule.render | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            {{- include "overviewer.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: render
        spec:
          restartPolicy: OnFailure
          containers:
            - name: render
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - -c
                - /overviewer/config.py
              volumeMounts:
                - mountPath: /var/lib/minecraft/world
                  readOnly: true
                  name: world
                - mountPath: /overviewer
                  name: config
                - mountPath: /overviewer/webassets
                  name: webassets
                - mountPath: /usr/share/nginx/html
                  name: map
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: config
              configMap:
                name: {{ include "overviewer.fullname" . }}-config
            - name: webassets
              configMap:
                name: {{ include "overviewer.fullname" . }}-webassets
            - name: world
              {{- toYaml .Values.worldVolume | nindent 14 }}
            - name: map
              persistentVolumeClaim:
                claimName: {{ include "overviewer.fullname" . }}
{{- end }}
{{- if .Values.schedule.genpoi }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "overviewer.fullname" . }}-genpoi
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
    app.kubernetes.io/component: render
spec:
  schedule: {{ .Values.schedule.genpoi | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 60
      template:
        metadata:
          labels:
            {{- include "overviewer.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: render
        spec:
          restartPolicy: OnFailure
          containers:
            - name: genpoi
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - -c
                - /overviewer/config.py
                - --genpoi
              volumeMounts:
                - mountPath: /var/lib/minecraft/world
                  readOnly: true
                  name: world
                - mountPath: /overviewer
                  name: config
                - mountPath: /usr/share/nginx/html
                  name: map
          volumes:
            - name: config
              configMap:
                name: {{ include "overviewer.fullname" . }}
            - name: world
              {{- toYaml .Values.worldVolume | nindent 14 }}
            - name: map
              persistentVolumeClaim:
                claimName: {{ include "overviewer.fullname" . }}
{{- end }}
{{- end }}
