apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  pdns.conf: |
    master=yes
    slave=no
    {{- if not .Values.webserver.enabled }}
    webserver=no
    {{- else }}
    webserver=yes
    webserver-address={{ .Values.webserver.address }}
    webserver-allow-from={{ .Values.webserver.allowFrom }}
    {{- if .Values.webserver.api }}
    api=yes
    {{- end }}
    {{- end }}
    launch=gpgsql
    gpgsql-dnssec=yes
    gpgsql-host={{ .Values.gpgsql.host }}
    gpgsql-dbname={{ .Values.gpgsql.dbname }}
