apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ip }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - name: dns
      port: {{ .Values.service.dnsPort }}
      targetPort: dns
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.service.dnsPort }}
      targetPort: dns-tcp
      protocol: TCP
    {{- if and .Values.webserver.enabled }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    {{- end }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
