apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns
      protocol: UDP
      name: dns
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
